# Generated by Django 6.0 on 2025-12-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="workout",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to a workout session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diary_entries",
                to="workouts.workoutsession",
            ),
        ),
    ]
