# Generated by Django 6.0 on 2025-12-08 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("shoulders", "Shoulders"),
                            ("biceps", "Biceps"),
                            ("triceps", "Triceps"),
                            ("legs", "Legs"),
                            ("core", "Core"),
                            ("full_body", "Full Body"),
                            ("cardio", "Cardio"),
                        ],
                        default="full_body",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "sets",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "reps",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of reps (null for time-based exercises)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in seconds (for time-based exercises)",
                        null=True,
                    ),
                ),
                (
                    "rest_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Rest time between sets in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        blank=True, help_text="Target weight in kg", null=True
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("flexibility", "Flexibility"),
                            ("mixed", "Mixed"),
                            ("hiit", "HIIT"),
                            ("yoga", "Yoga"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Duration in weeks",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_per_week",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Training Plan",
                "verbose_name_plural": "Training Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPlanAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Plan Assignment",
                "verbose_name_plural": "User Plan Assignments",
            },
        ),
    ]
