# Generated by Django 6.0 on 2025-12-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="plans.trainingplan",
            ),
        ),
    ]
